#ifndef HTTP_RESPONSE_CODE_H
#define HTTP_RESPONSE_CODE_H

enum HTTPResponseCode {
    HTTP_RESPONSE_CODE_UNDEFINED = 0,
    SUCCESS_OK = 200,
    SUCCESS_NO_CONTENT = 204,
    BAD_REQUEST = 400,
    FORBIDDEN = 403,
    SERVER_INTERNAL_ERROR = 500
};

#endif